import React, { useState } from 'react';
import { Icon } from './Icon';

interface Project {
  title: string;
  category: string;
  image: string;
  description: string;
}

const projectsData: Project[] = [
  {
    title: 'PathShala AI',
    category: 'Full-Stack & GenAI',
    image: '/assets/images/project-1.jpg',
    description: 'A personalized career advisor platform built from scratch. Utilized Next.js, React, and MongoDB to deliver dynamic, multi-step learning roadmaps automatically generated by integrated Gemini models.',
  },
  {
    title: 'SynEthica',
    category: 'Machine Learning & MLOps',
    image: '/assets/images/project-2.png',
    description: 'An advanced synthetic data generation system designed to securely scale training data. Leveraged Generative AI architectures and differential privacy techniques to produce secure datasets.',
  },
  {
    title: 'Enterprise RAG & Multi-Agent Orchestration',
    category: 'Agentic AI & Backend',
    image: '/assets/images/project-3.jpg',
    description: 'An autonomous customer workflow system utilizing CrewAI, LangChain, and Llama 3. Integrated a high-throughput RAG pipeline with ChromaDB and Pinecone for vector search.',
  },
  {
    title: 'Predictive Vision Pipeline',
    category: 'Machine Learning & MLOps',
    image: '/assets/images/project-4.png',
    description: 'A comprehensive deep learning pipeline using PyTorch (CNNs) achieving 95% accuracy. Productionized via scalable FastAPI endpoints and rapid UI demos with Streamlit.',
  },
];

const categories = ['All', 'Full-Stack & GenAI', 'Machine Learning & MLOps', 'Agentic AI & Backend'];

export const Portfolio: React.FC = () => {
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [dropdownActive, setDropdownActive] = useState(false);

  const handleCategoryChange = (category: string) => {
    setSelectedCategory(category.toLowerCase());
    setDropdownActive(false);
  };

  const filteredProjects = projectsData.filter((project) => {
    if (selectedCategory === 'all') return true;
    return project.category.toLowerCase() === selectedCategory;
  });

  return (
    <article className="portfolio active" data-page="portfolio">
      <header>
        <h2 className="h2 article-title">Portfolio</h2>
      </header>

      <section className="projects">
        {/* Desktop Filter List */}
        <ul className="filter-list">
          {categories.map((cat) => (
            <li key={cat} className="filter-item">
              <button
                className={selectedCategory === cat.toLowerCase() ? 'active' : ''}
                onClick={() => handleCategoryChange(cat)}
              >
                {cat}
              </button>
            </li>
          ))}
        </ul>

        {/* Mobile Filter Dropdown */}
        <div className="filter-select-box">
          <button
            className={`filter-select ${dropdownActive ? 'active' : ''}`}
            onClick={() => setDropdownActive(!dropdownActive)}
          >
            <div className="select-value">
              {categories.find((cat) => cat.toLowerCase() === selectedCategory) || 'Select category'}
            </div>
            <div className="select-icon">
              <Icon name="chevron-down" />
            </div>
          </button>

          <ul className="select-list">
            {categories.map((cat) => (
              <li key={cat} className="select-item">
                <button onClick={() => handleCategoryChange(cat)}>{cat}</button>
              </li>
            ))}
          </ul>
        </div>

        {/* Projects Grid */}
        <ul className="project-list">
          {filteredProjects.map((project, index) => (
            <li
              key={index}
              className="project-item active"
              style={{ 
                animation: `fade 0.5s ease-in-out`,
                cursor: 'default'
              }}
            >
              <div>
                <figure className="project-img">
                  <div className="project-item-icon-box" style={{ opacity: 0, transition: 'var(--transition-1)' }}>
                    <Icon name="eye-outline" />
                  </div>
                  <img src={project.image} alt={project.title} loading="lazy" />
                </figure>
                <h3 className="project-title" style={{ color: 'var(--white-2)', marginTop: '15px' }}>{project.title}</h3>
                <p className="project-category" style={{ color: 'var(--orange-yellow-crayola)', fontWeight: 'var(--fw-500)', fontSize: 'var(--fs-8)', marginBottom: '8px' }}>{project.category}</p>
                <p style={{ color: 'var(--light-gray)', fontSize: 'var(--fs-6)', lineHeight: '1.5', fontWeight: 'var(--fw-300)' }}>{project.description}</p>
              </div>
            </li>
          ))}
        </ul>
      </section>
    </article>
  );
};
